### ISSUE TITLE
Output if no scope defined

### ISSUE THREAD

**Issue by bradyclifford** [im-open/set-environment-variables-by-scope#10]
In cases where a yml file is being used and it is easier to define the majority of your values within that yml file or if you only need to set a different value for one or a couple scopes, can an additional input boolean be added that will output a value if no scope is defined at all?

```
output-non-scoped-values: true
```

This just makes it easier to set values that are the same for all scopes instead of defining all of the scopes. and also for those values that are shared between certain scopes.

```
TEAM_URI@prod: https://healthsherpa.com
TEAM_URI: https://staging.healthsherpa.com <- all remaining environments
```

It is just an easier way to define global values.  I get that you could do the same outside of this action.
```
TEAM_URI: ${{ steps.set-vars.outputs.TEAM_URI || 'https://staging.healthsherpa.com' }}
```

I am on the fence with this actually if it is worth it or not or even a good idea.

**Comment by hpractv** [comment]
From a file layout perspective, I'd rather have the scope specified.  Because we'd then have to run exception logic on all the variable regardless and then build the variable/scope dictionary out.

I don't think it's worth adding the ambiguity in.

**Comment by hpractv** [comment]
I don't think scopes are going to be set up very often, and the coding/syntax burden is low.

That being said, I'm not opposed to someone taking a stab at making a feature like this available.

**Comment by danielle-casella-adams** [comment]
Closing the stale issue.  If this is something that is desired you can always submit a PR.
