### ISSUE TITLE
console.log seems like a debugging leftover

### ISSUE THREAD

**Issue by mike-schenk** [im-open/set-environment-variables-by-scope#2]
https://github.com/im-open/set-environment-variables-by-scope/blob/cd2c38e502118449dd7950b508cff9b6886b8d4d/src/main.js#L15

You sure you want this left in here?

**Comment by danielle-casella-adams** [comment]
The subsequent comment on this line makes it seem like it was intentional.  I'm going to close this issue.

```js
console.log('Scoped Variables:', environmentDictionary); // This doesn't print right with JSON.stringify()
```
