### ISSUE TITLE
Grammar in warning message

### ISSUE THREAD

**Issue by mike-schenk** [im-open/set-environment-variables-by-scope#3]
https://github.com/im-open/set-environment-variables-by-scope/blob/cd2c38e502118449dd7950b508cff9b6886b8d4d/src/action_library.js#L47

This warning message is not clear.

maybe
```javascript
core.warning(`<<${e}>>:  was specified by both environment variable and input file. Environment variable will be used.`);
```

**Comment by danielle-casella-adams** [comment]
Warning updated in #23
