### ISSUE TITLE
Possible bug in scope handling

### ISSUE THREAD

**Issue by jahoyt-wtw** [im-open/set-environment-variables-by-scope#8]
After moving env vars to a yml file we started getting this error:

https://github.com/im-enrollment/underwriting/runs/4487754547?check_suite_focus=true
```
Run im-open/set-environment-variables-by-scope@v1.0.4
/opt/post-generation/actions-runner/_work/_actions/im-open/set-environment-variables-by-scope/v1.0.4/dist/index.js:6468.split(' ')
```

No var changes were made except moving them to a file. [Prior to that no error was generated](https://github.com/im-enrollment/underwriting/runs/4477329013?check_suite_focus=true). Looking at the code for the action it requires an @ in the vars. Adding the @ scopes fixed the issue.

I'm reporting this in case there is a silent failure occurring when vars are in the workflow or there may be different handling for vars in the workflow vs in a file.

**Comment by hpractv** [comment]
Let me make sure I understand what happened.
When it was in the `env` section, you had the key name like this `keyName: value` and it propagated to all the scopes?
When you moved it to a variable file you had to change it to `keyName@dev qa stage prod` to get the same behavior?

The behavior for the file is correct.  The `env` block should also always need the `@` as part of the key to split the applicable scopes.  Do you have an example of the workflow working without the `@` sign in the `env` block?

**Comment by mike-schenk** [comment]
As designed.

When the action uses environment variables for its input, it can't tell which environment variables were set specifically for its use and which ones are present for other reasons, so it can't enforce any naming restrictions on those variable names, and wouldn't be appropriate to warn about every other environment variable.

The `env` block on the step that calls this action doesn't make those environment variables special in any way. It's just a convenient way for the action to receive its dictionary of key-value inputs from the workflow file.
